# Generated by Django 5.1.6 on 2025-02-10 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plane_type', models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('Akinci', 'Akinci'), ('Kizilelma', 'Kizilelma')], max_length=20)),
                ('assembly_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Kanat', 'Kanat'), ('Govde', 'Govde'), ('Kuyruk', 'Kuyruk'), ('Aviyonik', 'Aviyonik')], max_length=20)),
                ('plane_type', models.CharField(choices=[('TB2', 'TB2'), ('TB3', 'TB3'), ('Akinci', 'Akinci'), ('Kizilelma', 'Kizilelma')], max_length=20)),
                ('department', models.CharField(choices=[('Kanat Takimi', 'Kanat Takimi'), ('Gövde Takimi', 'Gövde Takimi'), ('Kuyruk Takimi', 'Kuyruk Takimi'), ('Aviyonik Takimi', 'Aviyonik Takimi'), ('Montaj Takimi', 'Montaj Takimi')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UsedPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField()),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_parts', to='baykartryout.assembly')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baykartryout.part')),
            ],
        ),
    ]
