# Generated by Django 5.1.6 on 2025-02-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykartryout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
