# Generated by Django 5.1.6 on 2025-02-10 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baykartryout', '0002_part_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='name',
            new_name='part_name',
        ),
    ]
