# Generated by Django 5.1.6 on 2025-02-11 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykartryout', '0003_rename_name_part_part_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Kanat Takimi', 'Kanat Takimi'), ('Gövde Takimi', 'Gövde Takimi'), ('Kuyruk Takimi', 'Kuyruk Takimi'), ('Aviyonik Takimi', 'Aviyonik Takimi'), ('Montaj Takimi', 'Montaj Takimi')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
