# Generated by Django 5.1.6 on 2025-02-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baykartryout', '0004_usercred'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
